### PR TITLE
I have updated the README.md file

### PR DESCRIPTION
**Pull request by pratibhadixit549**
README.md has been updated.

### CODE REVIEW

**Comment by pratibhadixit549** [comment]
updated binary search, i.e., binary2.cpp with a better approach to find mid element

**Comment by pratibhadixit549** [comment]
file name modified from bubbleSort to bubbleSort.cpp

**Comment by pratibhadixit549** [comment]
bubble sort modified by adding  Boolean variable as a better approach.

**Comment by MukulCode** [comment]
closing since the conflicts were not resolved

**Pull request closed without merging**
